// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package querytest

import (
	"context"
)

type Querier interface {
	GetValues(ctx context.Context) ([]GetValuesRow, error)
}

var _ Querier = (*Queries)(nil)
